import Head from "next/head";
import React, { ReactNode } from "react";

type TLayout = {
  children?: ReactNode;
  name?: string;
};

export default function Layout({ children, name = "Home" }: TLayout) {
  return (
    <>
      <Head>
        <title>{`${name} | Management`}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="py-5 px-3">
        <h1 className="text-xl md:text-4xl text-center font-bold">
          Employee Management
        </h1>
        {children}
      </main>
    </>
  );
}
